DROP TABLE IF EXISTS OURKIDS.COMPLAINTS;

CREATE TABLE OURKIDS.COMPLAINT(
    ID              BIGINT          NOT NULL UNIQUE AUTO_INCREMENT, 
    NAME            VARCHAR(255)    NOT NULL,
    STATUS          BIT             NOT NULL DEFAULT 1,
    DESCRIPTION     VARCHAR(255),

    CONSTRAINT PK_COMPLAINT PRIMARY KEY (ID)
);